require: rubocop-rails

inherit_from: .rubocop.todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - config/initializers/*

Layout/LineLength:
  Max: 160
  AllowedPatterns:
    - '^ *#'
    - '\A#'
  Exclude:
    - db/migrate/*

Lint/AssignmentInCondition:
  Exclude:
    - db/migrate/20250131123310_add_service_name_to_active_storage_blobs.active_storage.rb

Metrics/AbcSize:
  Max: 19
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - spec/**/*
    - db/migrate/*

Metrics/MethodLength:
  Max: 40
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Exclude:
    - db/migrate/*

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20230122231501_add_jti_matcher_to_users.rb

Rails/Output:
  Exclude:
    - lib/generators/**/*.rb

Rails/ScopeArgs:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/20250131123310_add_service_name_to_active_storage_blobs.active_storage.rb

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
    - review

Style/Documentation:
  Enabled: false
