name: Deploy to staging

env:
  RAILS_ENV: staging
  DOCKER_REMOTE_BUILDER_IP: ${{ secrets.DOCKER_REMOTE_BUILDER_IP }}
  DOCKER_REMOTE_BUILDER_PRIVATE_KEY: ${{ secrets.DOCKER_REMOTE_BUILDER_PRIVATE_KEY }}
  SSH_STAGING_PRIVATE_KEY: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.SSH_STAGING_PRIVATE_KEY }}

      - name: Setup remote builder SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.DOCKER_REMOTE_BUILDER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "${{ env.DOCKER_REMOTE_BUILDER_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Configure AWS credentials and CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Ruby
        uses: ruby/setup-ruby

      - name: Install kamal
        run: gem install kamal

      - name: Run kamal envify targeting staging
        run: kamal envify -d staging

      - name: Run Kamal deploy targeting staging
        env:
          KAMAL_ENV: ${{ env.RAILS_ENV }}
          RAILS_ENV: ${{ env.RAILS_ENV }}
          DOCKER_BUILDKIT: 1
        run: kamal deploy -d staging
